CREATE TABLE IF NOT EXISTS CLOUD_COST_OPTIMIZATION (
    RESOURCE_ID STRING,
    RESOURCE_TYPE STRING,
    USAGE_HOURS FLOAT,
    COST FLOAT,
    STATUS STRING,
    REGION STRING,
    WASTE_COST FLOAT,
    RECOMMENDATION STRING
);
